- webpack.config.js
> Update webpack external

- .github/workflows/push-check.yml
Add xvfb to fix the error in tests on linux
> Add xvfb for linux tests

- src/extension/debugger/adapter/factory.ts
Related to: https://github.com/microsoft/vscode-python/issues/19482
> Fix error checking python version

- src/extension/debugger/configuration/dynamicdebugConfigurationService.ts
closed: https://github.com/microsoft/vscode-python-debugger/issues/39
> Update name in dynamic config

- package.json
- package.nls.json
- src/extension/debugger/configuration/resolvers/attach.ts
- src/extension/debugger/configuration/resolvers/launch.ts
- src/test/unittest/adapter/factory.unit.test.ts
- src/test/unittest/configuration/resolvers/attach.unit.test.ts
- src/test/unittest/configuration/resolvers/launch.unit.test.ts
- src/test/unittest/extensionInit.unit.test.ts
Closed: https://github.com/microsoft/vscode-python-debugger/issues/83
> Add global configuration for justMyCode

- src/extension/debugger/configuration/resolvers/attach.ts
- src/extension/debugger/configuration/resolvers/launch.ts
- src/test/unittest/configuration/resolvers/attach.unit.test.ts
- src/test/unittest/configuration/resolvers/launch.unit.test.ts
Closed: https://github.com/microsoft/vscode-python-debugger/issues/99
> Fix error in workspace

- src/extension/extensionInit.ts
Closed: https://github.com/microsoft/vscode-python-debugger/issues/142
> Focus current file before debugging

- README.md
Document supported versions of Python based in this comment: https://github.com/microsoft/vscode-docs/pull/6979#discussion_r1466647671
> Add version support table to README

- build/azure-pipeline.stable.yml
- package-lock.json
- package.json
> Finalized release 2024.0

- package-lock.json
- package.json
closed: https://github.com/microsoft/vscode-python-debugger/issues/70
closed: https://github.com/microsoft/vscode-python-debugger/issues/191
> Update some minor debt issues

- package.json
- src/extension/debugger/configuration/resolvers/base.ts
- src/extension/debugger/configuration/resolvers/launch.ts
- src/extension/telemetry/index.ts
- src/test/unittest/configuration/resolvers/launch.unit.test.ts
closed: https://github.com/microsoft/vscode-python-debugger/issues/154
> Open browser after launching

- package-lock.json
- package.json
Bumb release that uses debugpy 1.7
> bump release for py3.7 branch

- build/azure-pipeline.stable.yml
Verification build https://dev.azure.com/monacotools/Monaco/_build/results?buildId=260406&view=results
> chore: add APIScan field

- package-lock.json
- package.json
> bump dev version 2024.7

- SUPPORT.md
Updating `SUPPORT.md` file to match that within the vscode-python repo. Mapped to python SO and Discord since questions related to the debugger are filed there as well.
> Upadating SUPPORT.md

- .github/actions/build-vsix/action.yml
- .github/actions/lint/action.yml
- .github/workflows/pr-check.yml
- .github/workflows/push-check.yml
- build/azure-pipeline.pre-release.yml
- build/azure-pipeline.stable.yml
- debugpy_info.json
- src/extension/debugger/adapter/factory.ts
Update json to use debugpy 1.8.2
Update min python version supported to python 3.8
> Update debugpy version to 1.8.2

- src/extension/debugger/configuration/providers/fileLaunchWithArgs.ts
- src/test/unittest/configuration/providers/fileLaunchWithArgs.unit.test.ts
closed: https://github.com/microsoft/vscode-python-debugger/issues/233
> Fix error in args with default config

- package.json
- src/extension/extensionInit.ts
Closed: https://github.com/microsoft/vscode-python-debugger/issues/347
> Improve python debug welcome view

- package-lock.json
- src/extension/debugger/configuration/launch.json/launchJsonReader.ts
- webpack.config.js
- Read config from devcontainers too
- Fix local vsix creation
> Read launch config from devcontainers

- build/azure-pipeline.pre-release.yml
closed: https://github.com/microsoft/vscode-python-debugger/issues/290
> Update pre-release pipeline

- package.nls.json
Fix translations for the release
> Fix translation error

- package-lock.json
- package.json
Closes https://github.com/microsoft/vscode-python/issues/18097
> Don't show automatic debug config in virtual workspace

- src/extension/noConfigDebugInit.ts
- src/test/unittest/noConfigDebugInit.unit.test.ts
* fix no-config debugger env var insertion to be less noisy
> fix no-config debugger env var insertion to be less noisy

- bundled/scripts/noConfigScripts/debugpy.ps1
cherry pick this fix into the release
> fix powershell script for powershell no-config debug

- src/extension/telemetry/index.ts
part of https://github.com/microsoft/vscode-python-internalbacklog/issues/491
> switch telemetry event owner

- src/extension/debugger/configuration/launch.json/launchJsonReader.ts
- src/test/unittest/configuration/launch.json/launchJsonReader.unit.test.ts
fixes https://github.com/microsoft/vscode-internalbacklog/issues/5351
> fix bug to return empty array when no config exists

- src/extension/noConfigDebugInit.ts
cherry pick in clear env-vars for bug fix
> clear env var collection before adding new items (#659)

- src/extension/extension.ts
fixes https://github.com/microsoft/vscode-python/issues/25081
> expose getDebugpyPackagePath

- debugpy_info.json
> update debugpy to 1.8.16
