.flake8
.github/actions/build-vsix/action.yml
.github/actions/lint/action.yml
.github/dependabot.yml
.github/release.yml
.github/workflows/codeql-analysis.yml
.github/workflows/issue-labels.yml
.github/workflows/pr-check.yml
.github/workflows/pr-labels.yml
.github/workflows/push-check.yml
.vscode/settings.json
noxfile.py
package-lock.json
package.json
src/test/unittest/hooks/childProcessAttachHandler.unit.test.ts

Add GitHub labels

---

src/extension/debugger/hooks/childProcessAttachService.ts
src/test/unittest/hooks/childProcessAttachService.unit.test.ts

Refs: https://github.com/microsoft/vscode-python/issues/20376

Adopt lifecycle managed by parent

---

package.json
src/extension/common/constants.ts
src/extension/common/utils/localize.ts
src/extension/debugger/attachQuickPick/types.ts
src/extension/debugger/configuration/debugConfigurationService.ts
src/extension/debugger/configuration/providers/fastapiLaunch.ts
src/extension/debugger/configuration/providers/fileLaunchWithArgs.ts
src/extension/debugger/types.ts
src/extension/extensionInit.ts
src/extension/types.ts
src/test/unittest/configuration/providers/fileLaunchWithArgs.unit.test
src/test/unittest/extensionInit.unit.test.ts

closed: https://github.com/microsoft/vscode-python/issues/8876

Add python config with args

---

package.json
src/extension/debugger/debugPort/portAttributesProvider.ts
src/extension/extensionInit.ts
types/vscode.proposed.portsAttributes.d.ts
vscode.proposed.portsAttributes.d.ts

First part of the implementation of https://github.com/microsoft/vscode-python/issues/21292
- Register with the port forwarding API, and mark all ports as Ignore

Add port provider

---

noxfile.py

Use debugpy version 1.7.0 instead of latest

use version 1.7

---

src/extension/debugger/configuration/dynamicdebugConfigurationService.ts
src/extension/debugger/configuration/providers/djangoLaunch.ts
src/extension/debugger/configuration/providers/fastapiLaunch.ts
src/extension/debugger/configuration/providers/fileLaunch.ts
src/extension/debugger/configuration/providers/fileLaunchWithArgs.ts
src/extension/debugger/configuration/providers/flaskLaunch.ts
src/extension/debugger/configuration/providers/moduleLaunch.ts
src/extension/debugger/configuration/providers/pidAttach.ts
src/extension/debugger/configuration/providers/pyramidLaunch.ts
src/extension/debugger/configuration/providers/remoteAttach.ts
src/test/unittest/configuration/providers/djangoLaunch.unit.test.ts
src/test/unittest/configuration/providers/fastapiLaunch.unit.test.ts
src/test/unittest/configuration/providers/fileLaunch.unit.test.ts
src/test/unittest/configuration/providers/fileLaunchWithArgs.unit.test.ts
src/test/unittest/configuration/providers/flaskLaunch.unit.test.ts
src/test/unittest/configuration/providers/moduleLaunch.unit.test.ts
src/test/unittest/configuration/providers/pidAttach.unit.test.ts
src/test/unittest/configuration/providers/pyramidLaunch.unit.test.ts
src/test/unittest/configuration/providers/remoteAttach.unit.test.ts

closed: https://github.com/microsoft/vscode-python-debugger/issues/96

Remove default justMyCode

---

build/azure-pipeline.pre-release.yml
debugpy_info.json
debugpy_platforms.json
noxfile.py

Closed: https://github.com/microsoft/vscode-python/issues/20748

Platform-specific vsix

---

src/extension/telemetry/index.ts

These comments need to be JSON parseable which are not when `/` is included

Fix GDPR comments

---

src/extension/debugger/configuration/providers/djangoLaunch.ts
src/extension/debugger/configuration/providers/fastapiLaunch.ts
src/extension/debugger/configuration/providers/flaskLaunch.ts
src/extension/debugger/configuration/providers/moduleLaunch.ts
src/extension/debugger/configuration/providers/pyramidLaunch.ts
src/extension/debugger/configuration/providers/remoteAttach.ts
src/test/unittest/configuration/providers/djangoLaunch.unit.test.ts
src/test/unittest/configuration/providers/fastapiLaunch.unit.test.ts
src/test/unittest/configuration/providers/flaskLaunch.unit.test.ts
src/test/unittest/configuration/providers/moduleLaunch.unit.test.ts
src/test/unittest/configuration/providers/pyramidLaunch.unit.test.ts
src/test/unittest/configuration/providers/remoteAttach.unit.test.ts

Closed: https://github.com/microsoft/vscode-python-debugger/issues/223

Do not create config when esc is hit

---

src/extension/common/utils/localize.ts
src/extension/debugger/configuration/providers/flaskLaunch.ts
src/extension/debugger/configuration/providers/providerQuickPick/flaskProviderQuickPick.ts
src/extension/debugger/configuration/utils/configuration.ts
src/test/unittest/configuration/providers/flaskLaunch.unit.test.ts
src/test/unittest/configuration/providers/providerQuickPick/flaskProviderQuickPick.unit.test.ts

Closed: https://github.com/microsoft/vscode-python-debugger/issues/161

Improve debug config in flask

---

build/azure-pipeline.pre-release.yml
build/azure-pipeline.stable.yml

- Fix error with win-32. (https://dev.azure.com/monacotools/Monaco/_build/results?buildId=263944&view=logs&j=793f6990-16b1-5115-c944-576b3bbf7e39&t=89578552-e55c-5f0f-ce69-3edb63ae6858)
-  Add default platform in order to ficx this. (Closed: https://github.com/microsoft/vscode-python-debugger/issues/230 )

Fix platform-specific error

---

package-lock.json
package.json
src/extension/common/multiStepInput.ts
src/extension/debugger/configuration/providers/providerQuickPick/djangoProviderQuickPick.ts
src/extension/debugger/configuration/providers/providerQuickPick/flaskProviderQuickPick.ts
src/extension/debugger/configuration/providers/providerQuickPick/providerQuickPick.ts
tsconfig.json

Closed: https://github.com/microsoft/vscode-python-debugger/issues/286, https://github.com/microsoft/vscode-python-debugger/issues/287, https://github.com/microsoft/vscode-python-debugger/issues/289

Fix input error in django and flask pickers

---

src/extension/api.ts
src/extension/apiTypes.ts
src/extension/extension.ts
src/extension/extensionInit.ts
tsconfig.json

first part of: https://github.com/microsoft/vscode-python/issues/23032

Add api and send debugpy path

---

src/extension/debugger/hooks/debugpySocketsHandler.ts
src/extension/extensionInit.ts
src/test/runTest.ts
src/test/unittest/adapter/adapter.test.ts
src/test/unittest/adapter/factory.unit.test.ts
src/test/unittest/configuration/resolvers/base.unit.test.ts
tsconfig.json

Fix code annotations

---

package.json
src/extension/common/utils/localize.ts
src/extension/debugger/visualizers/inlineHexDecoder.ts
src/extension/extensionInit.ts
vscode.proposed.debugVisualization.d.ts

- Add button to show variables in hex

Show variables in hex

---

src/extension/common/process/rawProcessApis.ts

Fixes #245. A copy of the work at microsoft/vscode-python/pull/20741.

Fix debugger attach to process when running on WSL

---

package-lock.json
package.json
src/extension/telemetry/index.ts
src/extension/telemetry/reporter.ts
src/test/unittest/adapter/factory.unit.test.ts
src/test/unittest/index.ts
tsconfig.json

Fix npm vulnerability

---

src/extension/common/vscodeapi.ts
src/extension/debugger/inlineValue/pythonInlineValueProvider.ts
src/extension/extensionInit.ts
src/test/pythonFiles/testClassVarType.py
src/test/pythonFiles/testVarTypes.py
src/test/unittest/inlineValue/pythonInlineValueProvider.unit.test.ts

Closed: https://github.com/microsoft/vscode-python-debugger/issues/167

Show inline values

---

src/extension/debugger/inlineValue/pythonInlineValueProvider.ts
src/test/pythonFiles/testAssignmentExp.py
src/test/pythonFiles/testClassVarType.py
src/test/pythonFiles/testVarTypes.py
src/test/unittest/inlineValue/pythonInlineValueProvider.unit.test.ts

Closed: https://github.com/microsoft/vscode-python-debugger/issues/393

Update inline tests for all cases

---

src/extension/debugger/inlineValue/pythonInlineValueProvider.ts
src/test/pythonFiles/testVarTypes.py
webpack.config.js

- Fix error when a string has a name variable. Closed:https://github.com/microsoft/vscode-python-debugger/issues/401
- Fix webpack error. Closed: Closed: https://github.com/microsoft/vscode-python-debugger/issues/406

Fix some minor bugs

---

package.json
package.nls.json
src/extension/debugger/inlineValue/pythonInlineValueProvider.ts
src/extension/extensionInit.ts
src/test/unittest/inlineValue/pythonInlineValueProvider.unit.test.ts

Add setting for showing the inline values.

Add setting showPythonInlineValues

---

src/extension/debugger/inlineValue/pythonInlineValueProvider.ts
src/extension/extensionInit.ts
src/test/unittest/inlineValue/pythonInlineValueProvider.unit.test.ts

Closed: https://github.com/microsoft/vscode-python-debugger/issues/403
Closed: https://github.com/microsoft/vscode-python-debugger/issues/400

Only show readable variable types

---

src/extension/debugger/adapter/factory.ts
src/test/unittest/adapter/factory.unit.test.ts

fixes https://github.com/microsoft/vscode-python-debugger/issues/233

support interpreter paths with spaces

---

package.json
src/extension/debugger/configuration/resolvers/attach.ts
src/extension/debugger/configuration/resolvers/base.ts
src/extension/debugger/configuration/resolvers/launch.ts

As seen in this [issue](https://github.com/microsoft/debugpy/issues/1301), 'clientOS' is not an allowed entry in a launch.json. This PR adds the entry.

Support the clientOS property in VS code

---

src/extension/noConfigDebugInit.ts

increase discoverability of the new feature

add in description for no-config debug environment variable edits

---

src/extension/noConfigDebugInit.ts
src/test/unittest/noConfigDebugInit.unit.test.ts

sets env var 'PYDEVD_DISABLE_FILE_VALIDATION' as to not have extra output printed when debugpy is called

disable extra output for no config debug

---

src/extension/noConfigDebugInit.ts

fixes https://github.com/microsoft/vscode-python-debugger/issues/562

include debugpy in description

---

src/extension/noConfigDebugInit.ts

adds link to wiki page on no-config debugging to env var description

add link to wiki

---

bundled/scripts/noConfigScripts/debugpy
bundled/scripts/noConfigScripts/debugpy.bat
bundled/scripts/noConfigScripts/debugpy.fish
bundled/scripts/noConfigScripts/debugpy.ps1

switch shell scripts to use python3 from python for increased compatibility

switch to using python3 in the script for no-config debugging

---

src/extension/noConfigDebugInit.ts
src/test/unittest/noConfigDebugInit.unit.test.ts

fixes https://github.com/microsoft/vscode-python-debugger/issues/590

fix no-config debugger env var insertion to be less noisy

---

src/extension/noConfigDebugInit.ts

cherry-pick in "correct workspace path for mutiroot scenarios no-config debugging"

correct workspace path for mutiroot scenarios no-config debugging (#602)

---

src/extension/debugger/configuration/launch.json/launchJsonReader.ts
src/extension/debugger/configuration/launch.json/utils.ts
src/test/unittest/configuration/launch.json/launchJsonReader.unit.test.ts

fixes https://github.com/microsoft/vscode-python-debugger/issues/532

get launch config from settings.json as fallback

---

src/extension/debugger/configuration/providers/fileLaunchWithArgs.ts
src/test/unittest/configuration/providers/fileLaunchWithArgs.unit.test.ts

This PR is related to these issues:
https://github.com/microsoft/vscode/issues/225834
https://github.com/microsoft/vscode/issues/232560
https://github.com/microsoft/vscode-python-debugger/issues/233
https://github.com/microsoft/vscode-python-debugger/issues/465
https://github.com/microsoft/vscode-python-debugger/issues/497
I searched `repo:microsoft/vscode-python-debugger command:pickArgs` filtered by code, and find four snippet in thee files.
https://github.com/microsoft/vscode-python-debugger/blob/1b6ac0d2836a6288131de032e68d56f4770640e0/src/extension/debugger/configuration/providers/fileLaunchWithArgs.ts#L21-L27
https://github.com/microsoft/vscode-python-debugger/blob/1b6ac0d2836a6288131de032e68d56f4770640e0/src/test/unittest/configuration/providers/fileLaunchWithArgs.unit.test.ts#L28-L …

Make "args": "${command:pickArgs}" as default debug configuration

---

bundled/scripts/noConfigScripts/debugpy
bundled/scripts/noConfigScripts/debugpy.bat
bundled/scripts/noConfigScripts/debugpy.fish
bundled/scripts/noConfigScripts/debugpy.ps1
src/extension/noConfigDebugInit.ts

fixes https://github.com/microsoft/vscode-python-debugger/issues/617

fix bug with extension overriding debugpy endpoint

---

src/extension/debugger/configuration/resolvers/launch.ts
src/test/unittest/configuration/resolvers/launch.unit.test.ts

fixes https://github.com/microsoft/vscode-python-debugger/issues/580

respect existing serverReadyAction in launch config

---

src/extension/debugger/configuration/launch.json/launchJsonReader.ts

fixes same outcome as https://github.com/microsoft/vscode-internalbacklog/issues/5351. test example: https://github.com/rzhao271/python-debug-sandbox

switch to warning if launch.json missing version

---

src/extension/noConfigDebugInit.ts

fixes https://github.com/microsoft/vscode-python-debugger/issues/612

clear env var collection before adding new items

---

.github/workflows/codeql-analysis.yml
.github/workflows/pr-check.yml
.github/workflows/pr-labels.yml
.github/workflows/push-check.yml
.vscode/settings.json

Applies some [zizmor](https://docs.zizmor.sh/) audit suggestions to the workflows.

chore: lock down workflows

---

src/extension/noConfigDebugInit.ts
src/test/unittest/noConfigDebugInit.unit.test.ts

Fixes #691
The file watcher will trigger on the temp directory (when it is first created), throwing an error.

Fix `TypeError` from trying to read directory

---

src/extension/debugger/adapter/factory.ts

fixes https://github.com/microsoft/vscode-python-debugger/issues/712

update so deprecation shown for <3.9 not <=3.9
